#!/usr/bin/env python


try:
  # attempt to use the installed python package
  import stockquotes
except:
  # attempt to run the package from the source directory
  import sys
  sys.path.insert (0,'src')
  import stockquotes
  

if __name__ == '__main__':
    import sys
    sys.exit(stockquotes.main())
